app:
  port: 5050

mysql:
  UserName: "account"
  Password: "account"
  Address: "127.0.0.1:3306"
  DbName: "account"
  Charset: "utf8mb4"
  TimeOut: "10s" #连接超时，10秒
  MaxOpenConns: 100 #最大连接数
  MaxIdleConns: 20  #最大空闲连接数

redis:
  Host: "47.113.178.235"
  Port: 6379
  Password: "xsw21qaz"
  MaxRetries: 3
  DialTimeout: 10
  ReadTimeout: 10
  WriteTimeout: 10
  PoolSize: 30
  MinIdleConns: 20
